name: OnlineRewards
main: pers.tany.onlinereward.Main
version: 1.0.2
author: tany
depend: [ YukiNoaAPI ]
description: 每日玩家在线数量奖励
commands:
  OnlineRewards:
    usage: /OnlineRewards
    aliases: [ or,orr ]